'use client';
import DashNav from '@/app/components/dashnav';
import MediaWrapper from '@/app/components/media/wrapper';
import PageTitle from '@/app/components/pagesections/pagetitle';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';
import { spotifyBaseUrl } from '@/lib/types';
import { grabUsersHarborPlaylists } from '@/lib/utils/index';
import { useSession } from 'next-auth/react';
import React, { useEffect, useState } from 'react';

const Page = () => {
  const { data: session } = useSession();
  const [usersPlaylists, setUsersPlaylists] =
    useState<SpotifyApi.ListOfCurrentUsersPlaylistsResponse | null>(null);
  const [usersPlaylistsHarbor, setUsersPlaylistsHarbor] = useState<
    | {
        tracks: SpotifyApi.TrackSearchResponse[];
        playlistName: string;
        playlistCover: string;
      }[]
    | null
  >(null);
  useEffect(() => {
    async function grabUsersPlaylists() {
      const response = await fetch(`${spotifyBaseUrl}me/playlists`, {
        headers: {
          Authorization: `Bearer ${session!.accessToken}`,
        },
      });
      const responseData = await response.json();
      setUsersPlaylists(responseData);
    }
    async function grabUsersPlaylistsHarbor() {
      const response = await grabUsersHarborPlaylists(session!.user.uid);
      setUsersPlaylistsHarbor(response);
    }
    if (session) {
      grabUsersPlaylists();
      grabUsersPlaylistsHarbor();
    }
  }, [session]);
  return (
    <div className='page-container'>
      <DashNav />
      <ScrollArea className='w-full'>
        <section className='page-section'>
          <PageTitle title={'Playlists'} />
          {usersPlaylistsHarbor && (
            <MediaWrapper
              title={'Playlists Generated By Harbor'}
              type={'playlist-generated'}
              media={usersPlaylistsHarbor}
              overflow={false}
            />
          )}
          {usersPlaylists?.items && (
            <MediaWrapper
              title={'Playlists You Created'}
              information='Playlists from your spotify account'
              type={'playlist-user'}
              media={usersPlaylists}
              overflow={false}
            />
          )}
        </section>
        <ScrollBar orientation='vertical' />
      </ScrollArea>
    </div>
  );
};

export default Page;
